name: Dependency Updates

on:
  schedule:
    # Runs at 2 AM UTC every Monday
    - cron: '0 2 * * 1'
  workflow_dispatch: # Allows manual triggering

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: Update dependencies
        run: |
          ncu -u
          npm install

      - name: Run tests
        run: npm run test:run

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: '🔄 Automated dependency updates'
          body: |
            ## 📦 Dependency Updates
            
            This PR contains automated dependency updates.
            
            ### Changes
            - Updated package dependencies to their latest versions
            - All tests are passing ✅
            
            ### Review Checklist
            - [ ] Check for breaking changes in updated packages
            - [ ] Verify that all features still work as expected
            - [ ] Review changelog of major version updates
            
            **Auto-generated by GitHub Actions**
          branch: chore/dependency-updates
          delete-branch: true